version: '3.7'

services:

  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: 1q2w3e4r!
    ports:
      - 3307:3306
    volumes:
      - type: volume
        source: mariadb
        target: /var/lib/mysql
volumes:
  mariadb:
